springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/doc会自动重定向到swagger-ui.html页面
    path: /doc
    packages-to-scan: org.dows.hep.api
  group-configs:
    - group: hep-admin
      packagesToScan: org.dows.hep.rest.base
    - group: hep-tenant
      packagesToScan: org.dows.hep.rest.tenant
    - group: hep-user
      packagesToScan: org.dows.hep.rest.user


---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
springdoc:
  api-docs:
    enabled: false


---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
springdoc:
  api-docs:
    enabled: true

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true
---
#本地环境
spring:
  config:
    activate:
      on-profile: local
springdoc:
  api-docs:
    enabled: true