spring:
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/dow_uim_jx?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    dynamic:
      primary: hep #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      hikari:
        connection-timeout: 60000
        minimum-idle: 5
        maximum-pool-size: 10
        idle-timeout: 300000
        max-lifetime: 1200000
        auto-commit: true
        connection-test-query: SELECT 1
        validation-timeout: 3000
        read-only: false
        login-timeout: 5
      datasource:
        #数据源一
        hep:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://sh-cdb-1qjrazc8.sql.tencentcdb.com:63915/dxz?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: admin
          password: dxzsaas@!
        #数据源二
        uim:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://sh-cdb-1qjrazc8.sql.tencentcdb.com:63915/dxz?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: admin
          password: dxzsaas@!
---
#测试环境
spring:
  config:
    activate:
      on-profile: test
  datasource:
    dynamic:
      primary: hep #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      hikari:
        connection-timeout: 60000
        minimum-idle: 5
        maximum-pool-size: 10
        idle-timeout: 300000
        max-lifetime: 1200000
        auto-commit: true
        connection-test-query: SELECT 1
        validation-timeout: 3000
        read-only: false
        login-timeout: 5
      datasource:
        #数据源一
        hep:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.60:3307/dows_aicodea?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: 123456
        #数据源二
        uim:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.60:3307/dows_aicodea?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: 123456
---
#本地环境
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://101.35.194.46:3306/nezhadb?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: 7fFsECXmpjX5y3Xw
