oss:
  local:
    enable: true
    ossConfig:
      volumed:
        basePath: /data/resources/images/hep
        slice-config:
          task-num: 8
          part-size: 104857600

## windows
#oss.local.enable = true
#oss.local.ossConfig.volumnd.basePath = d:/images
#oss.local.ossConfig.volumnd.slice-config.task-num = 8
#oss.local.ossConfig.volumnd.slice-config.part-size = 104857600
#spring.mvc.static-path-pattern=/**
#spring.resources.static-locations=file:D