rade:
  oss:
    minio:
      enable: true
      access-key: PHTHKEPBYYD079K90B0O
      secret-key: ya35DAaNmtMKm0m7Yntdwj8m1p5ud+3fQ2kM5XDn
      bucket-name: hep
      base-path: /
      endpoint: http://192.168.1.60:9000
      slice-config:
        task-num: 8
        part-size: 104857604 # 1024*1024*100
  #  local:
  #    enable: true
  #    basePath: E:/fileTest
  #    slice-config:
  #      task-num: 8
  #      part-size: 104857600 # 1024*1024*100
  #
  #    ossConfig:
  #      volumnd:
  #        basePath: d:/fileTest
  #        slice-config:
  #          task-num: 8
  #          part-size: 104857600 # 1024*1024*100
  #      volumne:
  #        basePath: e:/fileTest
  #        slice-config:
  #          task-num: 8
  #          part-size: 104857600 # 1024*1024*100
  #  tencent:
  #    enable: true
  #    region: ap-shanghai
  #    secret-key:
  #    secret-sequence:
  #    bucket-name: cop-cloud-esign
  #    base-path: /
  #    slice-config:
  #      task-num: 8
  #      part-size: 104857604 # 1024*1024*100


