rade:
  encryptor:
    enable: true
    algorithm: AES
  oss:
    tencent:
      enable: true
      region: ap-shanghai
      secretId: encrypted$qI4rlDXFGL4/MjIP1rZJ+PjvzIeMAWBqx7qKVHRgKAf4+OWjEvEYJT0mQCJOcVp1
      secretKey: encrypted$6QKfvveaxrjQ+5urdkhzdlQ6ixVCT5dTDNosjMp0jNgElP1iAdy6DIgzbSUbffzj
      bucket-name: radeorg2025-1350162118
      base-path: /resume
      endpoint: myqcloud.com
      slice-config:
        task-num: 8
        part-size: 104857604
    minio:
      enable: true
      access-key: PHTHKEPBYYD079K90B0O
      secret-key: ya35DAaNmtMKm0m7Yntdwj8m1p5ud+3fQ2kM5XDn
      bucket-name: hep
      base-path: /
      endpoint: http://192.168.1.60:9000
      slice-config:
        task-num: 8
        part-size: 104857604 # 1024*1024*100
  #  local:
  #    enable: true
  #    basePath: E:/fileTest
  #    slice-config:
  #      task-num: 8
  #      part-size: 104857600 # 1024*1024*100
  #
  #    ossConfig:
  #      volumnd:
  #        basePath: d:/fileTest
  #        slice-config:
  #          task-num: 8
  #          part-size: 104857600 # 1024*1024*100
  #      volumne:
  #        basePath: e:/fileTest
  #        slice-config:
  #          task-num: 8
  #          part-size: 104857600 # 1024*1024*100



