---
#开发环境
spring:
  config:
    activate:
      on-profile: local
  redis:
    redisson:
      #file: redisson.yml
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          address: "redis://192.168.1.60:6399"
          password: redis7
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 2
          dnsMonitoringInterval: 5000
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  redis:
    redisson:
      #file: redisson.yml
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          address: "redis://192.168.1.60:6399"
          password: redis7
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 2
          dnsMonitoringInterval: 5000
        codec: !<org.redisson.codec.JsonJacksonCodec> {}